name: DALES compilation CI (OpenACC)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install common dependencies
        run: |
          # Enable sources for netcdff-dev
          sudo sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"

          sudo apt-get update
          sudo apt-get install -y cmake libnetcdf-dev environment-modules

      - name: Install NVHPC SDK
        run: |
          curl https://developer.download.nvidia.com/hpc-sdk/ubuntu/DEB-GPG-KEY-NVIDIA-HPC-SDK | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg
          echo 'deb [signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | sudo tee /etc/apt/sources.list.d/nvhpc.list
          sudo apt-get update -y
          sudo apt-get install -y nvhpc-23-11

      - name: Checkout NetCDF-Fortran
        uses: actions/checkout@v2
        with:
          repository: Unidata/netcdf-fortran
          ref: v4.6.1
          path: netcdf-fortran

      - name: Compile NetCDF-Fortran
        run: |
          source /etc/profile.d/modules.sh
          module load /opt/nvidia/hpc_sdk/modulefiles/nvhpc/23.11
          cd netcdf-fortran
          NCDIR=/usr FC=$(which nvfortran) ./configure --disable-shared
          sudo make -j 2
          sudo make install

      - name: Compile DALES
        run: |
          source /etc/profile.d/modules.sh
          module load /opt/nvidia/hpc_sdk/modulefiles/nvhpc/23.11
          sudo ln -s $(which nvfortran) /usr/bin/nvfortran
          mkdir build
          cd build
          SYST=NV-OpenACC cmake -DCMAKE_BUILD_TYPE=DEBUG -DUSE_NVTX=True ..
          sudo make -j 2
